### ISSUE TITLE
Safari dotdotdot problem

### ISSUE THREAD

**Issue by piaNINo4kA** [FrDH/jQuery.dotdotdot#129]
Strange thing appear in safari (10.0.3)
When I reload the page, it's working whatever in wants

.spheres-item
                    img(src="static/img/img1.jpg").spheres-image
                    .spheres__content
                        .spheres__title Wills & Estate Planning
                        .spheres__delimiter
(it's on pug)

.spheres__title {
  font-family: $extraboldFont;
  padding-bottom: 21px;
  color: #363636;
  font-size: 24px;
  line-height: 30px;
  max-width: 83%;
  max-height: 250px;
}
$('.spheres__title').dotdotdot({
 });
Picture1
<img width="838" alt="2017-09-19 18 40 38" src="https://user-images.githubusercontent.com/25428893/30601230-1cc07e68-9d6a-11e7-9791-ca17e018e2f7.png">
Picture2
<img width="861" alt="2017-09-19 18 40 28" src="https://user-images.githubusercontent.com/25428893/30601231-1cc320e6-9d6a-11e7-97cf-80e00a240368.png">
Picture3
<img width="856" alt="2017-09-19 18 40 47" src="https://user-images.githubusercontent.com/25428893/30601266-3240b8e8-9d6a-11e7-9883-e16f9338b70e.png">

**Comment by FrDH** [comment]
Is there an online example of the issue I could have a look at?

**Comment by piaNINo4kA** [comment]
Yes, sure
Right now i found it even in chrome
http://markup.com.dev11.vintagedev.com.ua/SmartAgreements/02_Legal-areas.html
