### ISSUE TITLE
3.0.3 not working.

### ISSUE THREAD

**Issue by reigelgallarde** [FrDH/jQuery.dotdotdot#131]
as the title says.

fiddle for 2.0.1 http://jsfiddle.net/kcemztok - working
fiddle for 3.0.3 http://jsfiddle.net/kcemztok/1/ - not working

**Comment by FrDH** [comment]
Thank you for reporting the issue.
The problem seems to be, that the text is directly inside the wrapper. If  you wrap the text in a HTML node (for example a `<SPAN>`), it works: http://jsfiddle.net/kcemztok/6/

I'll see if I can fix it shortly, for now you could wrap the text in a `<SPAN>`

**Comment by FrDH** [comment]
Should be fixed in 3.0.4
Could you please check?
