### ISSUE TITLE
Truncate when element becomes visible

### ISSUE THREAD

**Issue by rlenders** [FrDH/jQuery.dotdotdot#133]
I'm using `watch: 'window'`. In my setup, elements with dotdotdot are initialized before they are visible. As a result, nothing is truncated until the window was resized manually. This used to work in version 1.8.3. but doesn't work anymore in 3.0.4.

I looked at the source and confirmed my suspicion, elements are truncated on initialize, and every window resize event (if visible). There is no code that ensures the first truncate waits until the element becomes visible.

I realize it is impossible to do the truncate calculations before the element is visible, and I also realize there is no visibility event that we can wait for. I would suggest 2 improvements:

1. If the element is not visible during initialization, use a recurring timeout (similar to `watch: true`) and truncate the element when it becomes visible. (I assume this is what 1.8.3 did?)

2. Allow us manually call truncate. I know where in my script the element becomes visible, so allowing my to call truncate right after making it visible would be a great help. (What happened to `.trigger('update.dot')`?)

**Comment by FrDH** [comment]
1) I thinks in this case `watch: true` should work. (the interval should detects when the DIV becomes visible)
2) You can manually truncate the DIV using the API (it replaced the custom events):
http://dotdotdot.frebsite.nl/#api
````js
// fire the plugin
var $dot = $("#wrapper").dotdotdot();

// get the API
var API = $dot.data( "dotdotdot" );

// manually truncate
API.truncate();
````

**Comment by rlenders** [comment]
Even though `watch: true` works, I'd like to keep using `watch: 'window'` because the truncate seems more responsive that way.

I entirely missed the API section of the documentation, thanks for pointing that out! With `API.truncate()`, I can achieve what I want. I'll call it whenever my script makes the element visible.
