### ISSUE TITLE
Add truncateIfResized function to API object

### ISSUE THREAD

**Issue by RudeySH** [FrDH/jQuery.dotdotdot#136]
`API.truncate` always performs a truncate operation, even though the size of the element might not have changed. The API object could use a method that checks if the sizes had changed, and if so, performs the truncation. Basically, the method should do what the watch listeners already do, but on demand.

The reason I need this is because I have an element that can be hidden and shown dynamically. If the window size was changed while the element was hidden, and the element is shown again, I need to call `API.truncate`. This works, however if the window size hadn't changed, this still performs the truncate operation, even though it shouldn't have to do that.

What do you think?

**Comment by FrDH** [comment]
I guess that makes sense. Thanks for sharing.

**Comment by rlenders** [comment]
Any thoughts on the pull request?

**Comment by FrDH** [comment]
Sorry for the late reply, but I think `watchNow` isn't a good name, it implies a watch will be started.
The most logic would be to add an argument to the `truncate` method that determines whether or not to first check if the sizes are changed. Something like this:
````js
truncate = function( force )
{
    if ( force || this._watchSizes() )
    {
        
    }
}
````
This would mean I have to rewrite some of the watch logic.
I'll try to implement this in the next release.

**Comment by RudeySH** [comment]
Sounds good!
