### ISSUE TITLE
Newer version don't work in IE11. What's the official browser support?

### ISSUE THREAD

**Issue by rlenders** [FrDH/jQuery.dotdotdot#138]
After upgrading from 1.8.3 to 3.0.4, multi-line truncation no longer works properly in IE11. Elements with 2 lines of text are only 1 line after truncation. Elements with only 1 line of text dissapear, even though their max-height is high enough to allow 2 lines of text to fit.

And next to the truncation errors, I also noticed the performance is much worse than what I'm used to from 1.8.3. I have a page with exactly 100 dotdotdot elements, and loading/resizing is noticeably bad.

I've got some questions.

1. Was IE11 support dropped?
2. What's the official browser support?
3. What refactor could've caused performance issues?
4. If I go back to using an old version of this plugin, what sort of errors can I expect?

**Comment by FrDH** [comment]
I can't really think of any reason for IE11 to not function correctly, I don't think the plugin does anything browser-specific. Do the examples that come with the download have the same issue in IE11?

There are two changes that might have slowed down the truncate process:
* During the truncate process, text-nodes are wrapped in a `<span>`
* Truncating text-nodes starts at the end of the string removes words untill the text fits. This will slow the process down if your original text overflows a lot.

Having 100 elements truncated seems like quite a lot, the plugin isn't (and never was) intended to do so. You might want to consider simply using `overflow: hidden` and only trigger the `truncate()` process when an element is about to come into view (I can recommend [waypoints](http://imakewebthings.com/waypoints/) for that).

Hope this helps.

**Comment by rlenders** [comment]
Good to know that's how the truncate process works. I was using `truncate: 'letter'` instead of `'word'`, I can imagine `'letter'` slows it down even more. There should be a better way of truncating though, but I'm not sure how. If I think of anything I'll be sure to submit a PR.

> I don't think the plugin does anything browser-specific

Calculating widths and heights can lead to different results per browser, maybe the use of `getComputedStyle` is the culprit? But instead of guessing I'll do some investigation now.

**Comment by FrDH** [comment]
The plugin compares the current height using `$..innerHeight()` to the max-height using `Math.min( window.getComputedStyle( element )[ "height" ], window.getComputedStyle( element )[ "maxHeight" ])`

**Comment by rlenders** [comment]
I realized I was having two separate issues, one on my end which caused the difference between browsers.

The other issue is that `max-height` doesn't work with this plugin as expected. See #148.
