### ISSUE TITLE
Submit older versions to npm (because they were submitted to bower)

### ISSUE THREAD

**Issue by rlenders** [FrDH/jQuery.dotdotdot#139]
When migrating from bower to npm, I noticed the version of jQuery.dotdotdot I was using (1.8.3) was not available on npm. Strangely enough, 1.7.4 **is** available on npm.

If submitting all older versions to npm is too much work, consider submitting 1.8.3 only. It's the last version before 2.0.0, many people are likely to be using 1.8.3. And besides, to anyone using an old version other than 1.8.3 and 1.7.4, upgrading to 1.8.3 shouldn't cause any issues.

**Comment by FrDH** [comment]
That's odd, I think 1.8.3 should be on there, but it isn't. I'll have a look at how to publish an older version to NPM.
Thanks for the heads up.

**Comment by FrDH** [comment]
1.8.3 is now available on NPM
