### ISSUE TITLE
Callback function for v3

### ISSUE THREAD

**Issue by sectsect** [FrDH/jQuery.dotdotdot#142]
Thanks for Useful Plugin.

In version 2, callback function could be set as below, but it does not seem to work fine in v3.

```js
jQuery(element).dotdotdot({
  watch: 'window',
  wrap: 'letter',
  callback: function(isTruncated, orgContent) {

  }
});
```

**Comment by FrDH** [comment]
Good point, I'll add the callback in the next version.

**Comment by FrDH** [comment]
Check the latest version (3.1.0) and the docs: http://dotdotdot.frebsite.nl/#options

**Comment by sectsect** [comment]
Great. It works fine :tada:
Thanks for quick response.
