### ISSUE TITLE
Where gone options?

### ISSUE THREAD

**Issue by AlbertRAR** [FrDH/jQuery.dotdotdot#143]
Hi, i recently updated plugin from v2 to v3 and notised that some options disappeared from the plugin so my instances of ddd became broken. Also there is no present of changelog in github . For example i cant find such options as height, callback etc. Can you give some explanation and write changelog?

**Comment by FrDH** [comment]
Hi, sorry about the broken functionallity, but it is a major update.
For all available options, please visit the documentation website:
dotdotdot.frebsite.nl#options

The height option was removed in favor of using the CSS value for the height. Basically, you should use CSS to set a (max-)height:
````css
.my-div {
    max-height: 100px;
}
````

A callback option will be added in the next release:
https://github.com/FrDH/jQuery.dotdotdot/issues/142

**Comment by FrDH** [comment]
In the new release (3.1.0), you can now (once again) set a callback function and height option.
Check the documentation site for mor info:
http://dotdotdot.frebsite.nl/#options

**Comment by AlbertRAR** [comment]
that's good, thanks!

**Comment by AlbertRAR** [comment]
Also it will be great if you define default values of options on site, now it is unclear, if user should add option parameter or it set by default.

**Comment by FrDH** [comment]
The documentation shows the default values.
