### ISSUE TITLE
It works weirdly while truncate mandarin character

### ISSUE THREAD

**Issue by MonsAllyAlex** [FrDH/jQuery.dotdotdot#144]
![image](https://user-images.githubusercontent.com/33859967/33062397-235482be-ceda-11e7-88f5-86fe378759ec.png)

From the image you can observer that the 1st row, it truncated the object title nicely according to the height i set, but when you look at the 2nd object on the 2nd row, the truncated title is too short, as the full title of the object is shown below, i don't know why it cannot truncate the title like how the 1st row do.

![image](https://user-images.githubusercontent.com/33859967/33062576-ba5e590a-ceda-11e7-846a-b31c25ff5288.png)

**Comment by FrDH** [comment]
What version of the plugin are you using?
Is there an online example I could have a look at? I can't really do any debugging based on a screenshot.

**Comment by MonsAllyAlex** [comment]
it is version 2.0.0 @FrDH

**Comment by MonsAllyAlex** [comment]
Not sure if you are still viewing this post, but can you help me on this bug? Please and thanks

**Comment by FrDH** [comment]
Have you tried updating to v3.0?

**Comment by MonsAllyAlex** [comment]
Hi Fred,

After reading your email, I checked the version of dotdotdot.js in our
system. It is 3.0.2 at first and I updated it to 3.1.0 now, But, the
truncating Chinese word issue still exists. Here is the link to the
website: http://v2.tantannews.com/home. Thanks for replying my post and
hope to hear good news from you soon about the issue.

Yours Sincerely,
Alex

**Comment by FrDH** [comment]
Could you give 3.2.1 a try?
