### ISSUE TITLE
Clearer documentation

### ISSUE THREAD

**Issue by heyavery** [FrDH/jQuery.dotdotdot#147]
The previous documentation has clearer instructions and examples of what to expect with certain options. The new/current one leaves me very confused about what I should do. 

I wanted to replicate the example showed at the top of page that allows you to toggle the truncating feature, but it is unclear how to do it: manually add an anchor tag that fires the API or otherwise?

**Comment by FrDH** [comment]
Hi, thank you for the feedback. Having more detailed examples on the website is on the todo list.
For now, check index.html In the download pack, it has all three examples. The JS and CSS for those examples can be found in the source of index.html as well.

Hope this helps.
