### ISSUE TITLE
Newer versions break max-height

### ISSUE THREAD

**Issue by RudeySH** [FrDH/jQuery.dotdotdot#148]
I am using dotdotdot on a text container with `max-height: 100px`. My line height is 20px. Using an older version of this plugin (pre 2.0), this works as expected: the container's height is equal to **up to** 5 lines. So if the text fits on one line, the container's height is 20px. With 2 lines of text, the container's height is 40px, etc.

In the latest version the container will always have a height of 100px, regardless of how many lines of text there are in the container. Not only is this a change in behaviour of the plugin, it's also an undesired effect... max-height no longer works as a maximum height, it's just a fixed height at this point.

This happens because the plugin calculates the container's height by taking `height` or `maxHeight` of the computed style, depending on which of those two properties is the smallest. This is incorrect. You can't get the actual height of the element by looking at the computed style when max-height is being used, [getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) should be used.

**Comment by FrDH** [comment]
I can't seem to reproduce the issue, tested using "index.html" in the download pack on FireFox and Chrome.
Are you using the latest version of the plugin?
