### ISSUE TITLE
'maxLength' is no more?

### ISSUE THREAD

**Issue by pirminis** [FrDH/jQuery.dotdotdot#152]
It was dropped in commit `092c2866b010ccf5537c3a4797ba074d59eb3d9a`

```
Author: FrDH <info@frebsite.nl>
Date:   Fri Sep 15 17:34:23 2017 +0200

    version 3

    completely rewritten
```

incredible, but why?

**Comment by FrDH** [comment]
The maxLength option was removed because it did not work properly. All it did was trim the text to a fixed number of characters:
````js
text.substr(0, options.maxLength);
````

You don't need a plugin to do that.

**Comment by pirminis** [comment]
Thank you for replying 👍 

It just disappeared so quickly, had to use `git bisect` to find the commit that removed this option.

I have no more questions!
