### ISSUE TITLE
Dotdotdot always truncates a single line

### ISSUE THREAD

**Issue by thomasbao12** [FrDH/jQuery.dotdotdot#154]
See the following codepen

https://codepen.io/thomasbao12/pen/LQVqwv?editors=1111

**Comment by danielgc** [comment]
And not even a single line... Even in the case that all words fit in the container, the ellipsis is added:

https://jsfiddle.net/ueabtf0c/

**Comment by FrDH** [comment]
Hi,
Thank you for reporting the issue.
Should be fixed in 3.2.2

**Comment by thomasbao12** [comment]
Awesome thanks!

**Comment by danielgc** [comment]
Yeah! Thx!!
