### ISSUE TITLE
Can't truncate single long text

### ISSUE THREAD

**Issue by hengsoo** [FrDH/jQuery.dotdotdot#155]
This is irrelevant to practical usage, however I found that dotdotdot was unable to  truncate a single long text (eg. loooooooooooooooooooooooooooooooooongtext) in `truncate: "word", "node” or “letter"`. Wonder if this type of longtext is able to truncate.

**Comment by FrDH** [comment]
Makes sense, the plugin was designed to truncate vertically overflowing text. If you want to truncate text on a single line, I'd advice using CSS ellipsis.
