### ISSUE TITLE
Different behavior in chrome vs firefox

### ISSUE THREAD

**Issue by cherner** [FrDH/jQuery.dotdotdot#156]
Hello!

Awesome plugin. 

Note sure if this is an issue or not, but it looks like the text is trimmed more in Chrome and Safari than it is in firefox.

**Comment by RudeySH** [comment]
Different browsers render fonts in different ways. What kind of difference are you seeing between browsers? If it's just a few words being trimmed that aren't trimmed in other browsers, it's probably not a bug, just a tiny inconvenience that can't be solved.

**Comment by cherner** [comment]
For what it's worth, on my `#element-to-truncate` element, I observe that it has the class `ddd-truncated` in Firefox, but not in Chrome.

**Comment by FrDH** [comment]
Is there an online example?

**Comment by cherner** [comment]
Incoming.
