### ISSUE TITLE
isTruncated doesn't seem to work

### ISSUE THREAD

**Issue by Batmensch** [FrDH/jQuery.dotdotdot#74]
I'm using dotdotdot in a dust template, being rendered in Backbone.js.  The ellipsis part works fine.  However, the check for truncation doesn't seem to work in this context.  Currently I'm just printing something to console.log if a truncation is detected, but it never seems to detect anything.  I'm very new to jquery, so some hints as to how to debug this would be appreciated.

```
<td class='lme_notebook_object_name_txt'><div class='task_notebook_partname'>{name}</div></td>
<script>$(document).ready(function() {
$(".task_notebook_partname").dotdotdot({
       ellipsis: "..."
});
    if ( $(".task_notebook_partname").triggerHandler( "isTruncated" ) )
    {
      console.log("truncation detected");
    } 
});
</script>
```

if {name} above is large enough the text is truncated.  But the console.log text is never printed.  There are no console errors.

**Comment by FrDH** [comment]
I ran the below test with all demos in the download pack, they all worked:
````javascript
alert( $('#dot1').triggerHandler( 'isTruncated' ) );
````

**Comment by Batmensch** [comment]
That's why I asked for some way to debug.  I don't know why isTruncated isn't firing.

**Comment by FrDH** [comment]
Do you have multiple `DIV`s with that classname?
If so, `triggerHandler` will only test the first `DIV` to be truncated. Try using an `.each()`.

**Comment by Batmensch** [comment]
No multiple divs.  And besides, even if there were, I'd get at least one console log entry anyway, wouldn't I?  And there's nothing.
