### ISSUE TITLE
npm publish update

### ISSUE THREAD

**Issue by justinhelmer** [FrDH/jQuery.dotdotdot#84]
creating a new issue since the one opened on Jan 6 has been closed: https://github.com/BeSite/jQuery.dotdotdot/pull/54

A quote from my [comment](https://github.com/BeSite/jQuery.dotdotdot/pull/54#issuecomment-127707151)

@FrDH - If you are interested in keeping npm up-to-date (very simple), just create an http://npmjs.com account and just npm publish your package. Since you have already created a package.json, you should be good to go.

@FrDH - If you are not interested in maintaining npm, maybe @ws-malysheva would be willing to help maintain it? The npm package dotdotdot is currently maintained by @ws-malysheva but is out-of-date (contains the 1.7.0 source).

**Comment by noirbizarre** [comment]
+1
This pull-request #83 should remove some warnings too.

**Comment by noirbizarre** [comment]
Hi !

Any plan to release to NPM ?
Right now, it does not allow us to properly use jQuery.dotdotdot from Browserify or Webpack.

**Comment by killanaca** [comment]
+1

**Comment by gil** [comment]
+1

I've tried installing directly from your repo, but there are some invalid characters on your package.json (+)

https://github.com/BeSite/jQuery.dotdotdot/blob/5b31f5b6971724c8304ef2c956ad9ebdf4e2a7ca/package.json#L7-L9
