### ISSUE TITLE
Text not updated when resizing

### ISSUE THREAD

**Issue by gRoberts84** [FrDH/jQuery.dotdotdot#89]
Hi there,

Whilst testing some breakpoints for a site I'm using ... on, I noticed that it isn't updating the text should the container or page resize?

http://jsfiddle.net/gRoberts/qeootsx1/

If you resize the frame to resize the content, shouldn't it automatically re-evaluate and redraw the ellipsis accordingly? 

You'll notice that by resizing the container and clicking the run button or refreshing, it will display the text correctly.

Thanks

Gav

**Comment by FrDH** [comment]
If you take a look at the options, you'll notice the `watch` option. It can be set to either `true` or `"window"`. Setting it to `true` will start an interval constantly updating the ellipsis. Setting it to `"window"` will update the ellipsis onWindowResize.
