### ISSUE TITLE
Multiple Issues with height property

### ISSUE THREAD

**Issue by JosephUrciuoli** [FrDH/jQuery.dotdotdot#90]
I currently am using dotdotdot in an Angular directive as can be seen below.

``` javascript
app.directive('dotdotdot', function($timeout){
        return {
            restrict: 'A',
            link: function(scope, element, attributes) {
                console.log('link');
                $timeout(function(){
                    element.dotdotdot({watch: true, wrap: 'word', height: 40,
                        callback: function(isTruncated, orgContent){
                            console.log('callback');
                            if($(this).parent().height() > 20){
                                $(this).parent().css({'vertical-align': 'top'});
                            } else {
                                $(this).parent().css({'vertical-align': 'text-bottom'});
                            }
                        },
                    });
                },200);
            }
        };
    });
```

It is added to a span element as can be seen below:

``` html
<div class="title-name chart" met-table-title-width ><span dotdotdot>{{metric.metricDisplay.metricName}}</span></div>
```

The first issue I am finding is that if I don't set height, none of the content displays in the div.  The second issue I am having is that I set my height such that it equals the size of two lines.  So in my case, one line of text in the span is 18px. I have my height set to 40 as to only accomodate two lines.  However, in certain cases when I am resizing my browser it will bleed to 3.  The last word holds on to its' ellipsis, but goes on to the third line.  Am I using the height option incorrectly?  I don't understand why it would go to 3 lines (randomly) on browser resize.

**Comment by FrDH** [comment]
If your element has no height, how should the plugin know where to stop showing text? Also, I think using a block element will work better than an inline element.
